model:
  channels: 32
  num_blocks: 7
  semantic_classes: 13
  instance_classes: 13
  sem2ins_classes: [0, 1]
  semantic_only: False
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
    class_numpoint_mean: [1823, 7457, 6189, 7424, 34229, 1724, 5439,
                          6016, 39796, 5279, 5092, 12210, 10225]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
  fixed_modules: []

data:
  train:
    type: 's3dis'
    data_root: 'dataset/s3dis/preprocess'
    prefix: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
    suffix: '_inst_nostuff.pth'
    repeat: 5
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 's3dis'
    data_root: 'dataset/s3dis/preprocess'
    prefix: 'Area_5'
    suffix: '_inst_nostuff.pth'
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  dataloader:
    batch_size: 4
    num_workers: 4

optimizer:
  type: 'Adam'
  lr: 0.001

epochs: 512
step_epoch: 100
save_freq: 8
pretrain: 'hais_ckpt.pth'
work_dir: 'work_dirs/softgroup_scannet'
