GENERAL:
  task: train  # train, test
  manual_seed: 123
  model_dir: model/softgroup/softgroup.py
  dataset_dir: data/scannetv2_inst.py

DATA:
  data_root: dataset
  dataset: s3dis
  filename_suffix: _inst_nostuff.pth
  train_areas: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
  test_area: 'Area_5'
  train_repeats: 5

  semantic_classes: 13
  classes: 13
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50 -> voxel_size 0.02m
  batch_size: 4
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: softgroup
  width: 32
  block_residual: True
  block_reps: 2
  use_coords: True
  semantic_only: True

TRAIN:
  epochs: 30
  train_workers: 4 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.001
  step_epoch: 0
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 4  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, cls_loss, mask_loss, score_loss
  fg_thresh: 1.
  bg_thresh: 0.
  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 20  
  score_mode: 4 # mean
  pretrain_path: 'hais_ckpt.pth'
  pretrain_module: ['input_conv', 'unet', 'output_layer']
  fix_module: []


  point_aggr_radius: 0.04
  cluster_shift_meanActive: 300
  prepare_epochs: 10

  cal_iou_based_on_mask: True
  cal_iou_based_on_mask_start_epoch: -1

  use_mask_filter_score_feature: True
  use_mask_filter_score_feature_start_epoch: -1
  mask_filter_score_feature_thre: 0.5
  
  using_set_aggr_in_training: False
  using_set_aggr_in_testing: False

  max_proposal_num: 300
  max_clusters: 100

  iou_thr: 0.5
  score_thr: 0.2

TEST:
  split: val
  test_epoch: 100
  test_workers: 1
  test_seed: 567

  using_NMS: False
  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: -1
  TEST_NPOINT_THRESH: 100

  eval: True
  save_semantic: False
  save_pt_offsets: False
  save_instance: False

  test_mask_score_thre: -0.5 # bias fg << bg


  



